[workspace]
name = "tandem-r"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[dependencies]
r-base = ">=4.5"
r-testthat = "*"
r-jsonlite = "*"
r-roxygen2 = "*"
r-rcmdcheck = "*"
c-compiler = "*"
make = "*"
r-bit64 = ">=4.8.6,<5"
r-callr = ">=3.7.6,<4"

[tasks]
document = "Rscript -e 'roxygen2::roxygenise()'"
test = "Rscript -e 'testthat::test_local()'"
check = "Rscript -e 'rcmdcheck::rcmdcheck(args = c(\"--as-cran\", \"--no-manual\"), error_on = \"warning\")'"
install = "R CMD INSTALL --preclean ."
bench = { cmd = "Rscript tools/bench.R", depends-on = ["install"] }
